when:
  - event: push
  - branch: master

steps:
  - name: build and publish
    image: sunpeek/poetry:py3.12-slim
    commands:
      - apt-get update && apt-get install -y make
      - make build
      - make publish
    environment:
      PYPI_USERNAME: "__token__"
      PYPI_PASSWORD:
        from_secret: PYPI_API_TOKEN
